# Generated by Django 4.0.3 on 2022-04-26 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_pubdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='wrtier',
            new_name='writer',
        ),
        migrations.AlterField(
            model_name='board',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 26, 9, 57, 5, 751982)),
        ),
    ]
